[workspace]
members = ["crates/core", "crates/ass", "crates/fonts", "crates/harfbuzz", "crates/cli", "crates/wasm"]
default-members = ["crates/cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.92"
license = "MIT"
publish = false

[workspace.dependencies]
assfonts-core = { path = "crates/core" }
assfonts-ass = { path = "crates/ass" }
assfonts-fonts = { path = "crates/fonts" }
assfonts-harfbuzz = { path = "crates/harfbuzz" }
ttf-parser = "0.25.1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"

[profile.release]
lto = "thin"
strip = "debuginfo"
