[package]
name = "assfonts-ass"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
assfonts-core.workspace = true
ass-core = { git = "https://github.com/MuXiu1997/ass-rs.git", rev = "3e7b1c2ab50e078badc215d1a8d9a503a7956abd", default-features = false, features = ["std", "analysis", "plugins"] }
