[package]
name = "assfonts-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "assfonts-wasm"
path = "src/main.rs"

[dependencies]
assfonts-core.workspace = true
assfonts-ass.workspace = true
assfonts-fonts.workspace = true
assfonts-harfbuzz.workspace = true
serde_json.workspace = true
serde.workspace = true
